apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh
  namespace: keycloak
spec:
  keycloakCRName: example-kc
  realm:
    clients:
      - adminUrl: '{{ .Values.rhdh.route }}'
        enabled: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - '{{ .Values.rhdh.route }}/api/auth/oidc/handler/frame'
        serviceAccountsEnabled: true
        clientId: {{ .Values.realm.rhdh.name }}
        authorizationServicesEnabled: false
        name: {{ .Values.realm.rhdh.name }}
        rootUrl: '{{ .Values.rhdh.route }}'
        secret: changeme
        webOrigins:
          - '{{ .Values.rhdh.route }}'
    displayName: RHDH Realm
    enabled: true
    realm: {{ .Values.realm.rhdh.name }}