apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh
  namespace: keycloak
spec:
  keycloakCRName: example-kc
  realm:
    clients:
      - adminUrl: {{ .Values.realm.rhdh.host }}
        enabled: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - {{ .Values.realm.rhdh.host }}/api/auth/oidc/handler/frame
        serviceAccountsEnabled: true
        clientId: {{ .Values.realm.rhdh.name }}
        authorizationServicesEnabled: false
        name: {{ .Values.realm.rhdh.name }}
        rootUrl: {{ .Values.realm.rhdh.host }}
        secret: changeme
        webOrigins:
          - {{ .Values.realm.rhdh.host }}
    displayName: RHDH Realm
    enabled: true
    realm: {{ .Values.realm.rhdh.name }}
    # Define roles
    serviceAccountRoles:
      - name: "realm-management: query-users"
        description: "Allows querying users"
      - name: "realm-management: query-groups"
        description: "Allows querying groups"
      - name: "realm-management: view-users"
        description: "Allows viewing users"