apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AQAqNTmkWnj5ew3Mr4V4/9jQ+muh60T/G5O6VL6RLd7p5Fuap4hkwMiNYERy8v8XNS54zF9h7wx1bsZmQobyyL6BZJmSiWK9y+WiTVmwiSyr1coJfjnCaw1fCqA3bUGYiGcnzppJaGPFBSJvZrgAuishSZCh6ktc5CJLLWL1H9h1iom6+2pRkhq4xCRwLLSwT6m+mqgbrm9c/msRieL8THwfwHm06v15s7ZKip1HzfAkeSANvSvcTShJC8wm+JiQ+Lvza9IoAnDUyvWbRNRdhtiOX4/Wnd9TvnT+ysg/+PxkQojaSVZqOm/ZByw85Opg+jIxHuIa2vp/01jNcWSM4TOej2Rk8cZFB7gpVSdQdpBWin3CGFXXnlhZ
    username: AQBU5FjhHH7CivFZOzJiAKJ6DEQ+ijqas7ntHlftTOBBGx58jEfFkq5EnUwNkWpTcAcbt2oPo5BmDCDNzuW9l6VPnXEC5ZAEVGX3mfqI+sZIuHI7kCF4XQyhlGS+Vi0rWOKroLMbdPtCu3n06rGrOUfQvoplLGPYbyz3dre/86iCKff6/ZH8vhY81JvVSQWF4LXvu3N/0FdyPgwAeUg0904GDhK5fKdsv6K2xwo1MVRibv4xf6LQ/XiZ+pqa4mdJtfz9QB8jNoWi0qZ+P/ITHDSX3iaJqRJrqLZnErm5R+X+sMKlwZIjZYEt5Cs4zeK9NcOlcrSZ4LAkPRT1oqJXZnoNk+oNOxa5d6iCz0qj1Ulw6cVygJ/lwN+0
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque

