apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AQBVzpl3kbjGxpo5OTtBq3K2Jlh4rQcvgmsQgYnDepUFTkLUBdCv3QuFl63jLNi3x8cxMMleGLfWUaZ6OijruDb73YOFic8nA7p9sRyzn4EL2rYs2GRg7MIg1N9vc4om6FvA43vzbw3LT37xI/9E1ouCwRimCkumi0g3RegM4R6wU6d6396VfGvNg4XKmLolpCU3T0wCMu2oZCViMShVTcoL89IVioRFQBwGvYx7jstzqvutG80BxNdOdoZZovvLpjEYS99W/jZ0I9Mi+WP4Ig0PCf+rdwZ8RHJRgPYYcJe8ULVwyVrb81gYsBK61Wf8ukB91AAVAfAcEKhHuFDzpymkw4t54VigG6wcIOUsnhxsV3coEp8YBNnFgAQtGA==
    username: AQAoKOB5L/gAtQYgHyK8kGEquYNDdMC2lK+7r0ajM2QHSlxlZuAZpqrrz1VDZ9VOCOxkW9EP+2YMywgzsmEjWT5Bda5jnXAST4wuxzkRjr+5P1ZlrwSacOMfkDEUqKaLQk0LN8b36hSl+EstNh8udT2CfOe1mVv2oIEX4GZ2STyzE/q7fJ5p4HzkzYOEU3+934KFP7HJF6OIuZK/6c5OivxfcASjyqH58XPVkLgQnGEV4VfgMxtAwepb0GdbnJ6TK23GCrA98V5JidErmS7StLtvExMkMel4GxsL9PNTR0MTBxVn4FGHcKeWTApykDj1a/l81bKGlfiZc+93VqEnTSZtwGwbbsRYVYDVFk2Ipbt1ufR8qqWKzLhA
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque

